#!/bin/bash

set -e

initfile=/opt/icinga2/init.done

if [ ! -f "${initfile}" ]; then
        echo "Starting DB schema import. This might take a while (20sec+)."
        mysql_install_db --user=mysql --ldata=/var/lib/mysql 2>&1 >/dev/null
        /usr/bin/mysqld_safe 2>&1 >/dev/null &
        sleep 10s
        mysql -uroot -e "CREATE DATABASE IF NOT EXISTS icinga ; GRANT ALL ON icinga.* TO icinga@localhost IDENTIFIED BY 'icinga';"
        mysql -uicinga -picinga icinga < /usr/share/icinga2-ido-mysql/schema/mysql.sql
        mysql -uroot -e "CREATE DATABASE IF NOT EXISTS icingaweb2 ; GRANT ALL ON icingaweb2.* TO icingaweb2@localhost IDENTIFIED BY 'icingaweb2';"
        mysql -uicingaweb2 -picingaweb2 icingaweb2 < /usr/share/doc/icingaweb2/schema/mysql.schema.sql
        mysql -uicingaweb2 -picingaweb2 icingaweb2 -e "INSERT INTO icingaweb_user (name, active, password_hash) VALUES ('icingaadmin', 1, '\$1\$iQSrnmO9\$T3NVTu0zBkfuim4lWNRmH.');"
        killall mysqld
        sleep 10s

        echo "Fix volume permissions."
	# icinga2
        chown -R icinga:root /etc/icinga2
	mkdir -p /var/run/icinga2
	mkdir -p /var/log/icinga2
	chown icinga:icingacmd /var/run/icinga2
	chown icinga:icingacmd /var/log/icinga2
	mkdir -p /var/run/icinga2/cmd
	chown icinga:icingacmd /var/run/icinga2/cmd
	chmod 2750 /var/run/icinga2/cmd
        chown -R icinga:icinga /var/lib/icinga2
	usermod -a -G icingacmd apache >> /dev/null
	# icingaweb2
        chown root:icingaweb2 /etc/icingaweb2
        chmod 2770 /etc/icingaweb2
        mkdir -p /etc/icingaweb2/enabledModules
        chown -R apache:icingaweb2 /etc/icingaweb2/*
        find /etc/icingaweb2 -type f -name "*.ini" -exec chmod 660 {} \;
        find /etc/icingaweb2 -type d -exec chmod 2770 {} \;

        echo "Enabling icinga2 features."
        # enable icinga2 features if not already there
        icinga2 feature enable ido-mysql command

        echo "Enabling icingaweb2 modules."
        if [[ -L /etc/icingaweb2/enabledModules/monitoring ]]; then echo "Symlink for /etc/icingaweb2/enabledModules/monitoring exists already...skipping"; else ln -s /usr/share/icingaweb2/modules/monitoring /etc/icingaweb2/enabledModules/monitoring; fi
        if [[ -L /etc/icingaweb2/enabledModules/doc ]]; then echo "Symlink for /etc/icingaweb2/enabledModules/doc exists already...skipping"; else ln -s /usr/share/icingaweb2/modules/doc /etc/icingaweb2/enabledModules/doc; fi

        touch ${initfile}
fi

echo "Starting Supervisor."
echo "CTRL-C won't stop the container from running with or without the -d (daemon) option."
/usr/bin/supervisord -c /etc/supervisord.conf >> /dev/null
